### ISSUE TITLE
[readme] i need help

### ISSUE THREAD

**Issue by caspervanneck** [ServerSoftwareArchive/ClearSky#1]
i can not do it alone plz help team @AppleDevelo @xZeroMCPE @AnkitM252

**Comment by caspervanneck** [comment]
plz add travis

**Comment by NFGamerMC** [comment]
I am only managing ImagicalMine, Tesseract, and other

**Comment by caspervanneck** [comment]
@NFGamerMC your not

**Comment by caspervanneck** [comment]
@NFGamerMC i help you whit ImagicalMine, Tesseract

**Comment by NFGamerMC** [comment]
What I mean is I am the magaer for travis, and ci alsong with web. Do you need travis?

**Comment by caspervanneck** [comment]
ooo i getit sorry

**Comment by caspervanneck** [comment]
yes

**Comment by NFGamerMC** [comment]
Also, I fixed the glitter link in Tesseract. I made a error in the URL

**Comment by NFGamerMC** [comment]
We can chat on tesseract gitter
